package DTO;
// Generated 15-11-2016 03:06:05 PM by Hibernate Tools 3.6.0



/**
 * Nota generated by hbm2java
 */
public class Nota  implements java.io.Serializable {


     private Integer idNota;
     private Alumno alumno;
     private int nota;

    public Nota() {
    }

    public Nota(Alumno alumno, int nota) {
       this.alumno = alumno;
       this.nota = nota;
    }
   
    public Integer getIdNota() {
        return this.idNota;
    }
    
    public void setIdNota(Integer idNota) {
        this.idNota = idNota;
    }
    public Alumno getAlumno() {
        return this.alumno;
    }
    
    public void setAlumno(Alumno alumno) {
        this.alumno = alumno;
    }
    public int getNota() {
        return this.nota;
    }
    
    public void setNota(int nota) {
        this.nota = nota;
    }




}


